[package]
name = "advent"
version = "0.1.0"
authors = ["Giampiero Sciarra <giampiero.sciarra@prima.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.2"